services:
  - type: web
    name: english-phrase-api
    runtime: docker
    region: oregon
    rootDir: backend
    dockerCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    preDeployCommand: python manage.py migrate
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: english-app-db
          property: connectionString
      - key: SENDGRID_API_KEY
        sync: false
      - key: R2_ACCESS_KEY
        sync: false
      - key: R2_SECRET_KEY
        sync: false
      - key: R2_BUCKET_NAME
        value: english-phrase-media
      - key: R2_PUBLIC_BASE_URL
        sync: false
      - key: R2_SIGNING_ENDPOINT
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: noreply@eitango.club
      - key: CORS_ALLOWED_ORIGINS
        sync: false
